# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "dAC/rYBIBFS6tc8wAbZyCZQPiPvDDtqaZD3LMToNv9rv9JLER7lEYgkzf4iVu5m6JE89X4RZvCVDz26wEzdluPyRPVdMlhmUqoNHQqokTH0EpqJhbqKSPGbtVWoo9+2ZpH46gLipgSYNtvMUIhJUgSQ6bJuyb+zVRVh/ZTar05rmeUwEzV2G8Y9fFf3ADy4pkyqNVl0KJlp9BmdxrMvPdOz9e+pXPp55GGg0MvKe9W1cXs/in71KiinZ0UTaSgQVJYPK9mRCtSY3I5zLWUf3/hv/tpaAAsZWUh6BIKUX/t8IMEpwsxVXRFduTsMwySUKR0SI7n8F+PAGPgtKas9QTPy8TvwCcT7E8dFTpUpmvq2iidqZCzo1QlO/86hcQKaj9CADaX3WKqWZ1TVUvtXHalNZclNhqrotD0A2esPas3dHP2ORX8TyVec6SSmtDfydb5zZMzr5lWYHe6bBZGYQx9/P57d7yXjOU0pJDpi2/R4f3syH8z4MM3iWvF0nYmKIyw5o5cj7PdjAV9xIbfGDzr/KPYwfTt7RhOpJ+ACguqmbnOMPb4ermv8Qa/dsZPqQ5wxmWFJxVrIWVk5b+h5MkAMPSS/RtBY93SbxfxPrmOPuO8R04fj/j8hy3AH7x8urJlgjNA5vkfDu2WMUDU56GDrZs1w0o9o/CD8IlqijklE="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
